// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kapsknqpnhcofyfvznkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthcHNrbnFwbmhjb2Z5ZnZ6bmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDk1MzEsImV4cCI6MjA2MTY4NTUzMX0.w1wNquqXe8wErrcwiMgHeJPn6uDkJOpN8W9SJDuyCl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);